### PR TITLE
Build time dependency checking on pybind module files

### PR DESCRIPTION
**Pull request by mdavis36**
These changes should allow the make system to rebuild pybind modules whenever a *MOD.py file changes or any of its imported python files.

It works by generating an initial list of dependency files at configuration time that are then checked for changes during the build.

### CODE REVIEW

**Comment by jmikeowen** [comment]
So if we change the set of files imported by a *MOD.py file, does it automatically regenerate the set of dependencies?  I'm guessing it needs to rerun cmake?

**Comment by mdavis36** [comment]
@jmikeowen Correct if a file is added or removed it will rebuild the module (since the top parent file was changed), but if you make any changes later to that added file you will have to rerun cmake as make won't know the added file exists as a dependency. I don't know if there is a way to do build time dependency generation

**Comment by jmikeowen** [comment]
Hmm.  We should check it to be sure.  This would represent losing capability that works in autoconf, and there ought to be some way to fix this.

**Comment by mdavis36** [comment]
Okay, I'll look into this more then

**Comment by mdavis36** [comment]
Okay so the latest changes now seem to handle everything we want to do. It works by generating a cmake file that contains a list of the python deps during configure time. During build time the cmake file is regenerated and if any changes to the dependency list have been made it is replaced. This then prompts cmake to rerun a configure stage automatically, to make sure the new file is tracked as a dependency during build time. @jmikeowen

**Comment by jmikeowen** [comment]
This looks good to me -- I don't see any reason not to go ahead and merge it.

**Pull request merged**
